spring:
  #  DATABASE CONFIG
  datasource:
    password: sa
    url: jdbc:h2:mem:bookstore
    username: sa
    generate-unique-name: false
    name: bookstore
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    properties:
      hibernate:
        format_sql: ${SPRING_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never



book-store:
  security:
    jwt:
      refresh-token:
        expiration: 34
      expiration: 20
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970